### ISSUE TITLE
README 수정사항 발견

### ISSUE THREAD

**Issue by HelloDataScience** [bit2r/bitGPT#24]
안녕하세요? 최근에 공개해주신 패키지로 열심히 공부하고 있습니다. ^^
아래 README에서 오타로 보이는 것이 있어서 수정하는 것이 좋을 것 같습니다.
감사합니다!

```R
chat_completion("근의 공식을 설명해줘", type = "console")
══ Chat with chatGPT ══════════════════════════════════════════════════════ user ══
미세먼지가 많은 날은 어떻게 준비해야할까?

══ Chat with chatGPT ═════════════════════════════════════════════════ assistant ══
근의 공식은 다음과 같습니다.
```

**Comment by HelloDataScience** [comment]
조금 더 내려가면 type = 'messages'를 설명하면서 'text'로 잘못 표기되어 있습니다.
아마도 함수를 만드실 때 type에 지정할 수 있는 인수로 'text'를 사용하신 듯 한데요.
지금은 'messages', 'console', 'viewer'만 가능하다고 하니 'text'를 'messages'로 수정하셔야 될 것 같습니다.

> chat_completion("R의 가장 큰 장점은 무엇일까?.", type = "text")

**Comment by HelloDataScience** [comment]
이번에는 type = 'viewer' 관련입니다.
제가 아래와 같이 answer를 생성했는데 경로 에러가 났습니다.

# 메시지 생성
msg <- create_messages(
  system = '너는 Python과 R을 활용한 데이터 분석을 가르치고 질문에 대한 답변을 R과 Python 코드로 제공해',
  user = 'csv 파일을 읽고 데이터프레임을 생성하려면 어떻게 해야 하지?'
)

# 답변에 R 코드가 있을 때 유용
answer <- chat_completion(messages = msg, type = 'viewer')

에러 메시지를 읽어보니 제 컴퓨터에 아래 경로가 없다는 내용이었어요.
'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/bitGPT/images/gear.svg'

제 컴퓨터에서 해당 경로를 찾아보니 '4.2-arm64' 대신 '4.2'로 되어 있었습니다.
'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/bitGPT/images/gear.svg'

아무래도 제가 사용중인 맥미니가 예전(2018년도)에 산 것이라서 인텔 칩이라서 그런 듯 합니다.
글로벌 변수 목록에서 answer.Rmd를 열고 경로를 수정하면 knit를 할 수 있는데요. 아무래도 번거로워서요. 
이걸 편하게 수정하는 방법이 있을까요??

**Comment by choonghyunryu** [comment]
@HelloDataScience,

감사합니다.
검수가 안된 README는 수정해서 올렸구요.

마지막 이슈는 문제를 확인하고 대안을 만들어보겠습니다.

**Comment by choonghyunryu** [comment]
@HelloDataScience,

chat_completion() 함수의 Viewer 이슈 수정해서 올려두었습니다.

감사합니다.

**Comment by choonghyunryu** [comment]
@HelloDataScience,

이슈 클로징합니다.
