### ISSUE TITLE
기존 메시지를 추가하는 함수를 만들어보면 어떨까요?

### ISSUE THREAD

**Issue by HelloDataScience** [bit2r/bitGPT#25]
ChatGPT가 인컨텍스트 러닝을 한다고 알려져 있으니까 chat_completion() 함수 실행 결과를 받아서 사용자 프롬프트를 추가하는 함수가 있으면 더 낫지 않을까 싶어서요. 생각난 김에 오늘 아주 기초적인 함수를 만들어봤습니다. 제가 만든 함수보다 더 좋은 함수를 추가해주시면 대단히 감사하겠습니다. 
아래 코드는 전역 변수 목록에 messages가 없어도 새로 만들어서 대화를 이어나갈 수 있도록 해봤습니다. 제가 R 패키지를 만들어본 적이 없어서 함수를 이렇게 만들어도 되나 싶긴 합니다. ^^

```R

# messages에 assistant의 content를 추가하여 반환하는 함수 생성
keep_completion <- function(prompt, type = 'messages') {
  
  # messages 생성 또는 추가하여 전역 변수에 추가
  check_exist <- exists(x = deparse(expr = substitute(expr = messages)))
  if (!check_exist) {
    
    # messages가 없으면 prompt로 새 messages 생성
    messages <<- create_messages(user = prompt)
    
  } else {
    
    # messages가 있으면 user prompt 추가
    messages %>% add(user = prompt) ->> messages
    
  }
  
  # 채팅 형태로 질문에 답변(answer) 생성
  answer <- chat_completion(messages = messages, type = type)
  
  # 마지막 질문과 답변만 출력
  n1 <- length(x = answer)
  recent <- answer[(n1-1):n1]
  class(x = recent) <- c('messages', 'list')
  show(messages = recent)
  
  # 메시지에 assistant의 content 추가
  n2 <- length(x = messages)
  messages[[n2+1]] <<- list(
    'role' = 'assistant', 
    'content' = answer[[n1]]$content
  )
}

keep_completion(prompt = '지금 대한민국에서 가장 중요한 이슈가 뭐야?')
keep_completion(prompt = '그렇다면 현재 진행 중인 상태는 어떤가?')

```

**Comment by choonghyunryu** [comment]
@HelloDataScience,
좋은 의견 및 코드 감사드립니다.

사실 chat_completion() 함수 실행 결과를 받아서 사용자 프롬프트를 추가하는 함수로 `add()` 함수를 만들어 놓았습니다.
제공해 주신 예제 코드에 포함되어 있더군요.

HelloDataScience님의 코드
```
keep_completion(prompt = '지금 대한민국에서 가장 중요한 이슈가 뭐야?')
keep_completion(prompt = '그렇다면 현재 진행 중인 상태는 어떤가?')
```
가

이렇게 구현되는 것을 염두에 두었었습니다.
```
msg <- create_messages(user = "지금 대한민국에서 가장 중요한 이슈가 뭐야?")
msg <- chat_completion(msg, type = "console")
msg <- add(msg, user = "그렇다면 현재 진행 중인 상태는 어떤가?")
msg <- chat_completion(msg, type = "console")
``` 

매번 `add()` 함수로 메시지를 추가하고 다시 `chat_completion()` 함수를 호출하는 것이 불편하군요.
그리고 `chat_completion()` 함수는 모든 메시지 스레드를 출력해주는데, 마지막의 질문 메시지와 답변 메시지를 보여주는 것도 
효과적이네요.

HelloDataScience님의 제안대로 다음의 기능을 구현한 함수를 만들어 `keep_completion()` 이름으로 배포하겠습니다.

- 메시지를 함수 내에서 추가하는 기능
- 마지막 메시지 질문과 답변만 출력

보내주신 제안해주신 함수 코드를 살짝 손봐 차기 버전에 추가하겠습니다.

감사합니다.

**Comment by choonghyunryu** [comment]
bitGPT 0.3.6.9001 버전에서 구현했습니다.

**Comment by HelloDataScience** [comment]
우와 멋집니다. 그리고 감사합니다!!

**Comment by choonghyunryu** [comment]
이 이슈를 닫습니다.
