### ISSUE TITLE
GPT-3 모델 패러미터 초기값 설정

### ISSUE THREAD

**Issue by statkclee** [bit2r/bitGPT#32]
프롬프트 작성 시 주요 parameter에 대해 초기값(default)이 중요해 보입니다.

[챗GPT 패러미터](https://r2bit.com/chatGPT/prompt_in_practice.html#%EC%B1%97gpt-%ED%8C%A8%EB%9F%AC%EB%AF%B8%ED%84%B0) 및 openAI 스펙 확인해서 일반적인 값으로 지정해 보이는 것이 필요해 보입니다.

```
chat_completion(
  messages = NULL,
  model = "gpt-3.5-turbo",
  temperature = 1,
  top_p = 1,
  n = 1,
  stream = FALSE,
  stop = NULL,
  max_tokens = NULL,
  presence_penalty = 0,
  frequency_penalty = 0,
  logit_bias = NULL,
  user = NULL,
  type = c("messages", "console", "viewer"),
  openai_api_key = Sys.getenv("OPENAI_API_KEY")
)
```

**Comment by choonghyunryu** [comment]
@statkclee,

좋은 의견 감사합니다.

- 현재 Open API chat completion API는 "text-davinci-003"를 지원하지 않아서, 박사님의 문서를 참고하기는 어렵네요.
    - "gpt-3.5-turbo"가 "text-davinci-003"와 성능은 비슷하고 토큰당 가격이 10%라서 "gpt-3.5-turbo"를 추천한다네요.
    - "gpt-3.5-turbo"의 최적 초기 파라미터는 살펴보고 있습니다.
- 이즘에서 chat_completion()에 gpt-4대 모델을 추가해야할 것 같네요.
   - 현재는 c("gpt-3.5-turbo", "gpt-3.5-turbo-0301")만 지원합니다.

감사합니다.

**Comment by choonghyunryu** [comment]
현재 OpenAI API에서 gpt-4를 지원 안 하나보네요.

```
> bitGPT::list_models(unnest = TRUE) %>% filter(stringr::str_detect(id, "gpt"))
                  id object             created owned_by               root parent
1 gpt-3.5-turbo-0301  model 2023-03-01 05:52:43   openai gpt-3.5-turbo-0301     NA
2      gpt-3.5-turbo  model 2023-02-28 18:56:42   openai      gpt-3.5-turbo     NA
                       permission_id permission_object  permission_created allow_create_engine
1 modelperm-6AUS6aCU9HdoFz4S9TCfI4at  model_permission 2023-04-12 23:47:35               FALSE
2 modelperm-BmdmcAa1aQwToDxri3DFbZw9  model_permission 2023-04-12 23:47:35               FALSE
  allow_sampling allow_logprobs allow_search_indices allow_view allow_fine_tuning organization group
1           TRUE           TRUE                FALSE       TRUE             FALSE            *    NA
2           TRUE           TRUE                FALSE       TRUE             FALSE            *    NA
  is_blocking
1       FALSE
2       FALSE
```

**Comment by choonghyunryu** [comment]
@statkclee,

- Open AI의 [Playground](https://platform.openai.com/playground?mode=chat)를 참고하려 합니다.
- `gpt-3.5-turbo` 모델의 초기 값이 다음과 같이 설정되어 있군요.
    -  temperature = 0.7
    - Maximum length = 256
    - Top P = 1
    - Frequency penalty = 0
    - Presence penalty = 0
 
자신들이 만든 모델을 제일 잘아는 OpenAI가 Playground에 적용한 파라미터 초기값이 최적으로 설정해 놓은 것이라 생각됩니다. 
그래서 다음과 같이 설정하려 합니다.

어떻게 생각하세요, 박사님?

```
chat_completion(
  messages = NULL,
  model = c("gpt-3.5-turbo", "gpt-3.5-turbo-0301"),
  temperature = 0.7,
  top_p = 1,
  n = 1,
  stream = FALSE,
  stop = NULL,
  max_tokens = NULL,
  presence_penalty = 0,
  frequency_penalty = 0,
  logit_bias = NULL,
  user = NULL,
  type = c("messages", "console", "viewer"),
  openai_api_key = Sys.getenv("OPENAI_API_KEY")
)
```

**Comment by choonghyunryu** [comment]
@statkclee,

짧은 시간에 만들어 나가느라 뒤보다는 앞만 보고 달려서 그렇습니다.
함수 개발 당시 충분한 고민과 경험의 부족의 한계죠. 그리고, 한번 만들어논 함수는 쉽게 다시 쳐다보지 못합니다. 
진도를 빼는 것도 중요하지만 고민도 중요하는데...

목요일 미트업에서 이야기한 혼자 개발해서는 안된다는 이야기의 한 사례가 되었습니다.
감사합니다.
